language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script: bundle exec rspec
before_install:
    - gem update --system
    - gem install bundler